### ISSUE TITLE
Synapse Detection for 2-photon Calcium imaging data

### ISSUE THREAD

**Issue by akatav** [aksimhal/synapse-detection-examples#1]
Hi @aksimhal 
Thank you for this great repo here.I am working with 3d pre and post image stacks obtained using 2 photon Calcium imaging. The stacks have multiple channels, one for dendrite, one for synapse and others. Can I use your code on this data ?

**Comment by aksimhal** [comment]
It's hard to say without actually seeing the data first. If you post the data/code in a repo somewhere, I can take a look and let you know.

**Comment by akatav** [comment]
@aksimhal i can post a few sample frames. As for the code, I am using the example run_me python notebook with pre_IF set to {day-1} tif stack and post_IF set to {Day+2} stack. 
![900C4_day-1](https://user-images.githubusercontent.com/721570/112922550-9dbc4900-9147-11eb-999c-3391546634ed.gif)
![900C4_day+2](https://user-images.githubusercontent.com/721570/112922557-a0b73980-9147-11eb-9ed8-522fed30ef3b.gif)

These pre and post images are already preprocessed, motion corrected, aligned and undergone deconvolution.

**Comment by aksimhal** [comment]
I'm not sure it will work for those images since it appears that the axons/dendrites are strained as well. That might result in false positives.

**Comment by akatav** [comment]
@aksimhal  thank you for your valuable feedback.I really appreciate it.The images posted belong to the synapse channel.There is another channel that shows dendrites more than synapses.Is there a way i can use the dendrite channel images as some sort of reference to identify synapses in the synapse channel images?Would that help
